# Generated by Django 4.1.5 on 2023-01-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_service_description_remove_service_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
